### ISSUE TITLE
View Animation Problem Between ShortSounds

### ISSUE THREAD

**Issue by shampson** [nharlow89/ShortSounds#12]
If you are switching between two short sounds, the animation shows the effect view in the background while animating the change.  This might be changed by animation changes later

**Comment by shampson** [comment]
@jonesman107 Do you know the fix to this one?  I'm still seeing it for multiple cases of switching contexts

**Comment by Sigotron** [comment]
@jonesman107 

Start with empty ShortSound app. Record a track, set eq, save it, then create a new short sound, then load the previous one from the drawer. You can see the EQ effect screen in between animator transitions. You can see it in a lot of other transitions as well. It does not appear to happen with the REVERB effect screen though.
