### ISSUE TITLE
Effect Library Loaded Problem

### ISSUE THREAD

**Issue by shampson** [nharlow89/ShortSounds#25]
Error:
java.lang.UnsupportedOperationException: Effect library not loaded
        -Error code -5 (Invalid State)

Where:
-attachEffects() in AudioPlayer
        -Usually happens when app is overloaded
           -Example: Recorded 3 tracks on top of each other, then made new track and recorded

Possible Reason:
This could be due to not releasing tracks/effects when we are done with them

**Comment by nharlow89** [comment]
Think this was fixed during resource managment
