### ISSUE TITLE
Seek Bar not reseting after record.

### ISSUE THREAD

**Issue by jbuscher** [nharlow89/ShortSounds#27]
When recording multiple tracks, if track is recorded, and is shorter than the longest track in the ShortSound, the seekbar will not reset. Fix is to reset the seekbar after recording

**Comment by Sigotron** [comment]
Fixed. Made it so it doesn't move when its recording. It doesn't necessarily make sense to have it move anyways cause if you record a longer track than the longest then it just goes to the end and sits there.
