### ISSUE TITLE
Last Track Removed Doesn't Show Record A Sound! TextView

### ISSUE THREAD

**Issue by Sigotron** [nharlow89/ShortSounds#31]

**Comment by nharlow89** [comment]
The proper way to handle this would be to have a default view for the RecyclerView when it contains no elements. Also, other parts of the code can be made much cleaner with this implementation (mostly the create new button can actually create a new ShortSound!)
http://stackoverflow.com/questions/28217436/how-to-show-an-empty-view-with-a-recyclerview

**Comment by jonesman107** [comment]
I can do this right now

**Comment by Sigotron** [comment]
Fixed by @jonesman107.
