### ISSUE TITLE
Effects cause app crash when parameters changed

### ISSUE THREAD

**Issue by jonesman107** [nharlow89/ShortSounds#35]
This is a result of not dealing with the null case when enabling and disabling effects.  There needs to be some way of retrying the effect load and all effect methods need to check for null effects before using them.

**Comment by nharlow89** [comment]
It looks like this situation occurs when our application goes out of view (ie press home button), re-open the app, and then try messing with effects. Im guessing android is freeing up the effect resources on us? @jonesman107 Can you be more specific as to how you encountered this?

**Comment by shampson** [comment]
It was part of the cleanup. We found the issue and solved it.  Pushing to master soon
