### ISSUE TITLE
Swipe delete hard to keep hold of

### ISSUE THREAD

**Issue by jonesman107** [nharlow89/ShortSounds#40]
Sorry I am reopening this one because I really can't delete unless I move very slowly and carefully.  It needs to account for moving outside of the trackview's touch area in the y-direction.  Ideally if user did not lift their finger, moving outside of the view wouldn't matter.

**Comment by nharlow89** [comment]
Updated the threshold to trigger the delete, little more user friendly and will have to do for now.
