### ISSUE TITLE
Share track send might wav of length 0

### ISSUE THREAD

**Issue by jonesman107** [nharlow89/ShortSounds#42]
This is just an error handling thing.  We should check if the file is length 0 and retry parsing once or twice before cancelling the send or something like that.  It could also be an error with the share widget thus, outside of our control.  Either way we should check for that case and do something nice. :)

**Comment by caseyfischer** [comment]
Made it so we retry up to 5 times in createShareIntent if the file is null or of length 0.  Beyond that, let's blame the quick share if the recipient gets an empty file :)
