### ISSUE TITLE
If you record a bunch of tracks really fast the app crashes. Atypical Use Case.

### ISSUE THREAD

**Issue by jonesman107** [nharlow89/ShortSounds#43]

**Comment by nharlow89** [comment]
This doesn't seem like a realistic use case, probably shouldn't spend time on this today.

**Comment by jonesman107** [comment]
A fair point but the app shouldn't crash no matter what the user does.  It's worth tracking that this happens.

**Comment by jonesman107** [comment]
Can't record a bunch of tracks really fast anymore thanks to the countdown timer.
