### ISSUE TITLE
MediaPlayers are ALL setup on app load

### ISSUE THREAD

**Issue by nharlow89** [nharlow89/ShortSounds#8]
It doesn't make sense (and is actually a noticeable performance issue) to setup the MediaPlayers for every track when the app loads. In fact, we should ONLY have MediaPlayer's active for the tracks in the current active ShortSound. 
- Move the setUpMediaPlayer() method out of the ShortSoundTrack constructor (the db constructor)

**Comment by nharlow89** [comment]
Moved the setup of MediaPlayers to when the ShortSound is loaded into fragment

**Comment by caseyfischer** [comment]
What branch is this fix in?  I'm going to lazily set up effect resources as well and it looks like the MediaPlayer instances are still created in the ShortSoundTrack constructors in the master branch

**Comment by nharlow89** [comment]
Yeah sorry should have specified. Look in the backend model branch

**Comment by caseyfischer** [comment]
K thanks
