### ISSUE TITLE
Sidebar not updated with new ShortSound

### ISSUE THREAD

**Issue by nharlow89** [nharlow89/ShortSounds#9]
Think this was working the other day? But when creating a new ShortSound (by recording from the blank screen) the sidebar is not updated with the new ShortSound.

**Comment by mattiecarlson** [comment]
Replacing the last two lines of the if (isNewShortSound) branch with the following should fix this bug.  I've fixed it on my local branch, but I'm not ready to merge with master:
mDrawerList.setAdapter(new ArrayAdapter<String>(this,
                    R.layout.drawer_list_item, mShortSoundsTitles));
